FROM kasmweb/ubuntu-jammy-desktop@sha256:58b0710b320b99ab7e352342d7ec3a25b09740c523b75d794c5f7476910da580

USER root

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get purge -y \
      code firefox gimp gimp-data google-chrome-stable \
      nextcloud-desktop nextcloud-desktop-common nextcloud-desktop-doc nextcloud-desktop-l10n \
      obs-studio obs-v4l2sink onlyoffice-desktopeditors \
      remmina remmina-common remmina-plugin-rdp remmina-plugin-secret remmina-plugin-spice remmina-plugin-vnc \
      signal-desktop slack-desktop sublime-text thunderbird zoom \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /opt/Telegram \
      /home/kasm-default-profile/Desktop/* \
      /home/kasm-default-profile/.mozilla \
      /home/kasm-default-profile/.local/share/remmina

COPY infra/issue-006/onecomputer-agent.py /usr/local/bin/onecomputer-agent
COPY infra/issue-006/onecomputer-agent.desktop /usr/share/applications/onecomputer-agent.desktop
COPY infra/issue-006/onecomputer-agent.desktop /home/kasm-default-profile/Desktop/ONEComputer-Agent.desktop

RUN chmod 0755 /usr/local/bin/onecomputer-agent \
    /usr/share/applications/onecomputer-agent.desktop \
    /home/kasm-default-profile/Desktop/ONEComputer-Agent.desktop \
    && chown -R 1000:1000 /home/kasm-default-profile/Desktop

USER 1000
